version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    env_file: [".env"]
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    ports:
      - "${API_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt

# docker-compose.yml
  ingest:
    build: .
    env_file: [".env"]
    environment:
      - PYTHONPATH=/app
      - API_URL=http://api:8080    # <â€” point to the API service, not localhost
    depends_on:
      api:
        condition: service_started
    working_dir: /app
    volumes:
      - ./scripts:/app/scripts
      - ./app:/app/app
      - ./packages:/app/packages
    command: python scripts/ingest_any.py


volumes:
  pgdata:


